spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homework5
    username: root        # 본인 MySQL 아이디
    password: "비밀번호"      # 본인 MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

