spring:
  application:
    name: mutsa_week7_hw

  datasource:
    url: jdbc:mysql://localhost:3306/mutsa_db5?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: romance2521*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true