spring:
  application:
    name: session5
  datasource:
    url: jdbc:mysql://mutsa-db.c3yaueumiwe3.ap-northeast-2.rds.amazonaws.com:3306/mutsa_db
    username: uaeoon
    password: '490119ah'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080